# 실기시험1 (60)
---
* 과목: Python+빅데이터
* 이름:
* 날짜:

---
##**문제1** [ 넘파이 ] 슬라이싱 (25)
---

슬라이싱을 이용해 아래 조건에 맞게 넘파이 배열을 생성하는 코드를 작성하세요


<p align='center'>
<img src=https://github.com/yebiny/Lecture-Python-Data_analysis-LV1/blob/main/imgs/test-01.png?raw=true width=400>
</p>



In [3]:
import numpy as np


* 그림과 같은 2차원 배열을 `arange`와 `reshape`를 이용해서 생성하기 (5점)


In [ ]:
arr = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
print(arr,arr.shape)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]] (6, 6)


* 각 색깔에 해당하는 값으로 새로운 배열 생성하기 (각 5점씩 총 네가지 색깔)

In [ ]:
red = arr[0:6,2]
print(red,red.shape,"\n")

yellow = arr[0,3:5]
print(yellow,yellow.shape,"\n")

green= arr[(2,4),::2]
print(green,green.shape,"\n")

blue = arr[4:6,4:6]
print(blue,blue.shape)

[ 2 12 22 32 42 52] (6,) 

[3 4] (2,) 

[[20 22 24]
 [40 42 44]] (2, 3) 

[[44 45]
 [54 55]] (2, 2)


---
## **문제2** [ 파이썬 ] 점찍기 (10)
---

아래와 같은 출력을 하는 코드를 for 루프를 이용해서 작성하세요

```
 *  **********
 **  *********
 ***  ********
 ****  *******
 *****  ******
 ******  *****
 *******  ****
 ********  ***
 *********  **
 **********  *
```


In [ ]:
for i in range(10):
  star=["*","*","*","*","*","*","*","*","*","*","*","*"]
  star[i+1]=" "
  print(" ".join(star))


*   * * * * * * * * * *
* *   * * * * * * * * *
* * *   * * * * * * * *
* * * *   * * * * * * *
* * * * *   * * * * * *
* * * * * *   * * * * *
* * * * * * *   * * * *
* * * * * * * *   * * *
* * * * * * * * *   * *
* * * * * * * * * *   *


---
##**문제3** [ 파이썬 ] 홀짝 게임  (10)
---

홀짝게임을 만듭니다. 홀짝게임에서는 홀짝을 맞추면 베팅금액이 두배로 증가합니다. 맞춘 후 계속 진행을 할 수도 있고 더이상 진행하지 않고 두배금액을 획득할 수 있습니다. 만약 홀짝을 맞추지 못하면 돈을 잃고 게임이 종료됩니다. 

아래 예시를 만족하도록 코드를 작성하세요. 기본실행 코드 점수 10점이 부여됩니다.

* 코드실행 예 1

```
> 베팅금액을 입급하세요. 최소단위는 1000원 입니다.: 1000
> -----------------
> [*] 주사위 던지는 중
> ----------------- 
3..
2..
1..
> 홀/짝을 선택하세요: 홀
> 정답입니다. 현재 금액은 2000원 입니다.
> 계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.): 예
> -----------------
> [*] 주사위 던지는 중 
> -----------------
3..
2..
1..
> 홀/짝을 선택하세요: 홀
> 정답입니다. 현재 금액은 4000원 입니다.
> 계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.): 예
> -----------------
> [*] 주사위 던지는 중
> ----------------- 
3..
2..
1..
> 홀/짝을 선택하세요: 홀
> 틀렸습니다. 게임이 종료됩니다.
```
* 코드실행 예 2

```
> 베팅금액을 입급하세요. 최소단위는 1000원 입니다. : 1000
> ----------------
> [*] 주사위 던지는 중
> ---------------- 
3..
2..
1..
> 홀/짝을 선택하세요: 홀
> 정답입니다. 현재 금액은 2000원 입니다.
> 계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.): 아니오
> 2000원을 획득했습니다!
```

In [4]:
import time
import random

In [7]:
def game():
  money=input("베팅금액을 입급하세요. 최소단위는 1000원 입니다.:")
  while True:
    print(" -----------------\n[*] 주사위 던지는 중 \n-----------------" )
    타이머()
    select=input("홀/짝을 선택하세요 :")
    if select=="홀":
      select=1
    else:
      select=0
    if (random.randint(1,7))%2==select:
      money=int(money)*2
      print("정답입니다. 현재 금액은 {0}원 입니다.".format(money))
      more= input("계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.)")
      if more == "예":
        continue
      else:
        print("{0}원을 획득했습니다!".format(money))
        break
    else:
      print("틀렸습니다. 게임이 종료됩니다")
      break
  

def 타이머():
  t=3
  while t != 0:
    print(str(t)+"...")
    t-=1
    time.sleep(1)
game()

베팅금액을 입급하세요. 최소단위는 1000원 입니다.:0
 -----------------
[*] 주사위 던지는 중 
-----------------
3...
2...
1...
홀/짝을 선택하세요 :홀
정답입니다. 현재 금액은 0원 입니다.
계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.)아니오
0원을 획득했습니다!


---
##**문제4** [ 파이썬 ] 홀짝 게임 옵션추가 (15)
---

위에서 만든 기본 실행 코드에 다음과 같은 옵션을 추가하면 옵션 하나당 5점씩 추가됩니다.


1. 아래 주사위 던지는 시간이 실제로 3초가 걸리도록 한다.
```
> [*] 주사위 던지는 중 
3
2
1
```

2. 배팅 금액을 1000원 이하로 입력하거나 잘못된(문자열 등) 입력을 하면 "금액을 재입력 하세요" 메시지를 보내고 다시 입력을 받도록 한다.

3. 홀/짝 선택시 홀/짝 외에 잘못된 입력을 하면 "홀/짝 중 하나를 입력하세요" 메시지를 보내고 다시 입력을 받도록 한다.

위에서 만든 기본 코드는 그대로 두고 옵션을 추가한 코드는 아래에 다시 작성해 주세요. 어떤 옵션을 추가했는지 간단히 적어주세요


시간은 위에도 작성했었고 금액재입력 홀짝 재입력 추가했습니다 (모두 추가) 

In [6]:
def game():
  while True:
    money=input("베팅금액을 입급하세요. 최소단위는 1000원 입니다.:")
    if money.isdecimal() ==False or int(money)<1000:
      print("금액을 재입력하세요")
    else:
      break
  while True:
    print(" -----------------\n[*] 주사위 던지는 중 \n-----------------" )
    타이머()
    select=input("홀/짝을 선택하세요 :")
    if select != "홀" and select !="짝":
      print( "홀/짝 중 하나를 다시 입력하세요")
      continue
    else:
      if select=="홀":
        select=1
      else:
        select=0
      if (random.randint(1,7))%2==select:
        money=int(money)*2
        print("정답입니다. 현재 금액은 {0}원 입니다.".format(money))
        more= input("계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.)")
        if more == "예":
          continue
        else:
          print("{0}원을 획득했습니다!".format(money))
          break
      else:
        print("틀렸습니다. 게임이 종료됩니다")
        break
    
    

def 타이머():
  t=3
  while t != 0:
    print(str(t)+"...")
    t-=1
    time.sleep(1)
game()

베팅금액을 입급하세요. 최소단위는 1000원 입니다.:홀
금액을 재입력하세요
베팅금액을 입급하세요. 최소단위는 1000원 입니다.:1000
 -----------------
[*] 주사위 던지는 중 
-----------------
3...
2...
1...
홀/짝을 선택하세요 :아니
홀/짝 중 하나를 다시 입력하세요
 -----------------
[*] 주사위 던지는 중 
-----------------
3...
2...
1...
홀/짝을 선택하세요 :짝
정답입니다. 현재 금액은 2000원 입니다.
계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.)예
 -----------------
[*] 주사위 던지는 중 
-----------------
3...
2...
1...
홀/짝을 선택하세요 :아니
홀/짝 중 하나를 다시 입력하세요
 -----------------
[*] 주사위 던지는 중 
-----------------
3...
2...
1...
홀/짝을 선택하세요 :홀
정답입니다. 현재 금액은 4000원 입니다.
계속 진행하겠습니까? (예 를 입력하면 계속 진행합니다.)아니오
4000원을 획득했습니다!
